#!/usr/bin/env node
/**
 * Seeds the gotchas catalog (data/gotchas/*.json) into the best_practices table
 * so today's codra injects them into reviews. Prints SQL; pass --remote or
 * --local to apply via wrangler, otherwise it just writes the .sql file.
 *
 *   node scripts/ops/seed-gotchas.mjs            # write scripts/ops/gotchas.sql
 *   node scripts/ops/seed-gotchas.mjs --local    # + wrangler d1 execute --local
 *   node scripts/ops/seed-gotchas.mjs --remote   # + wrangler d1 execute --remote
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const catalogDir = path.resolve(__dirname, '../../data/gotchas');
const outFile = path.join(__dirname, 'gotchas.sql');
const DB_NAME = 'codra';

const sqlStr = (v) => `'${String(v).replace(/'/g, "''")}'`;

/** PlateJS instruction blocks so it renders in the /best-practices editor. */
function instructions(g) {
  const nodes = [
    { type: 'h3', children: [{ text: g.title }] },
    { type: 'p', children: [{ text: g.directive }] },
  ];
  if (g.fix_example) {
    nodes.push({ type: 'p', children: [{ text: 'Fix:' }] });
    nodes.push({ type: 'code_block', children: [{ type: 'code_line', children: [{ text: g.fix_example }] }] });
  }
  if (g.evidence) nodes.push({ type: 'p', children: [{ text: `Evidence: ${g.evidence}` }] });
  return JSON.stringify(nodes);
}

const files = fs.readdirSync(catalogDir).filter((f) => f.endsWith('.json'));
if (files.length === 0) {
  console.error('No gotcha JSON files found in data/gotchas/');
  process.exit(1);
}

const infraIds = new Set();
const rows = [];
for (const file of files) {
  const g = JSON.parse(fs.readFileSync(path.join(catalogDir, file), 'utf8'));
  const infra = (g.infra && g.infra[0]) || 'cloudflare-workers';
  infraIds.add(infra);
  // criteria terms: the human signal words + infra so matchesCriteria fires.
  const criteria = [...(g.infra || []), 'insert', 'values', 'batch']
    .join(', ');
  rows.push(
    `INSERT INTO best_practices (id, name, infra_id, criteria, instructions, is_active) VALUES (` +
      `${sqlStr('gotcha-' + g.id)}, ${sqlStr(g.title)}, ${sqlStr(infra)}, ${sqlStr(criteria)}, ${sqlStr(instructions(g))}, 1) ` +
      `ON CONFLICT(id) DO UPDATE SET name=excluded.name, infra_id=excluded.infra_id, criteria=excluded.criteria, instructions=excluded.instructions, is_active=1, updated_at=CURRENT_TIMESTAMP;`,
  );
}

const infraSql = [...infraIds]
  .map((id) => `INSERT INTO infrastructures (id, name) VALUES (${sqlStr(id)}, ${sqlStr(id)}) ON CONFLICT(id) DO NOTHING;`)
  .join('\n');

const sql = `-- Generated by scripts/ops/seed-gotchas.mjs from data/gotchas/*.json\n${infraSql}\n${rows.join('\n')}\n`;
fs.writeFileSync(outFile, sql);
console.log(`Wrote ${outFile} (${rows.length} gotcha rows).`);

const mode = process.argv.includes('--remote') ? '--remote' : process.argv.includes('--local') ? '--local' : null;
if (mode) {
  console.log(`Applying to D1 (${mode})...`);
  execFileSync('npx', ['wrangler', 'd1', 'execute', DB_NAME, mode, '--file', outFile], { stdio: 'inherit' });
}
