import { useEffect, useId, useState } from 'react';

interface MermaidDiagramProps {
  /** Mermaid source. Model-authored from PR content — treated as untrusted. */
  code: string;
  caption?: string;
}

/** mermaid.initialize must run once per page. */
let initialized = false;

/**
 * Renders a Mermaid diagram to inline SVG. `mermaid` is dynamically imported so
 * it stays out of the main bundle — only changelog pages pay for it.
 *
 * SECURITY: unlike an in-repo docs diagram, this source is generated by a model
 * from pull request content that the PR author controls. It is therefore
 * rendered with securityLevel 'strict' (mermaid escapes HTML in labels and
 * disables click handlers/script tags). Do not relax this to 'loose'.
 */
export function MermaidDiagram({ code, caption }: MermaidDiagramProps) {
  const reactId = useId();
  // Mermaid render ids must be valid CSS selectors — strip React's colons.
  const renderId = `mmd-${reactId.replace(/[^a-zA-Z0-9_-]/g, '')}`;

  const [svg, setSvg] = useState('');
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    async function render() {
      try {
        const mermaid = (await import('mermaid')).default;
        if (!initialized) {
          mermaid.initialize({
            startOnLoad: false,
            securityLevel: 'strict',
            theme: 'dark',
            fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
            themeVariables: {
              background: 'transparent',
              primaryColor: '#1c1c20',
              primaryBorderColor: '#3f3f46',
              primaryTextColor: '#fafafa',
              lineColor: '#71717a',
              secondaryColor: '#26262b',
              tertiaryColor: '#18181b',
              fontSize: '14px',
            },
          });
          initialized = true;
        }

        // parse() throws a readable error for malformed sources.
        await mermaid.parse(code);
        const { svg: rendered } = await mermaid.render(renderId, code);
        if (!cancelled) {
          setSvg(rendered);
          setError(null);
        }
      } catch (err) {
        if (!cancelled) setError(err instanceof Error ? err.message : 'Failed to render diagram');
      }
    }

    void render();
    return () => {
      cancelled = true;
    };
  }, [code, renderId]);

  return (
    <figure className="space-y-2">
      <div className="overflow-x-auto rounded-xl bg-card/40 p-4 ring-1 ring-border/40">
        {error ? (
          <pre className="whitespace-pre-wrap text-xs text-danger">Diagram error: {error}</pre>
        ) : svg ? (
          <div
            className="flex justify-center [&_svg]:h-auto [&_svg]:max-w-full"
            // SVG is produced by mermaid with securityLevel 'strict', which
            // escapes labels from the untrusted model-authored source above.
            dangerouslySetInnerHTML={{ __html: svg }}
          />
        ) : (
          <div className="py-8 text-center text-xs text-muted-foreground">Rendering diagram…</div>
        )}
      </div>
      {caption ? (
        <figcaption className="text-center text-xs font-light text-muted-foreground">{caption}</figcaption>
      ) : null}
    </figure>
  );
}
